# Generated by Django 5.1.6 on 2025-02-08 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0003_product_description_product_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(db_column='order_id', primary_key=True, serialize=False)),
                ('order_status', models.CharField(choices=[('PD', 'Pending'), ('CP', 'Completed'), ('CC', 'Canceled')], default='PD', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.AutoField(db_column='order_item_id', primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(db_column='transaction_id', primary_key=True, serialize=False)),
                ('transaction_status', models.CharField(choices=[('CP', 'Completed'), ('CC', 'Canceled')], default='CP', max_length=2)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='purchase.orderitem')),
            ],
        ),
    ]
