# Generated by Django 5.1.6 on 2025-02-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.AutoField(db_column='product_id', primary_key=True, serialize=False),
        ),
    ]
